@startuml

title Diagrama de Secuencia: Cambio a Mapa desde Menú

participant Vista
participant VistaMenu
participant VistaMapa
participant App

activate Vista
Vista -> VistaMenu: Usuario presiona el botón "JUGAR"
activate VistaMenu
VistaMenu -> App: Cambia a la escena del mapa
activate App
App -> App: Cargar FXML del mapa
App -> VistaMapa: Inicia Vista del mapa
activate VistaMapa
deactivate App
deactivate VistaMapa
deactivate VistaMenu
deactivate Vista

@enduml