@startuml

title Diagrama de Secuencia: Cambio a Menú desde Tutorial

participant Vista
participant VistaTutorial
participant VistaMenu
participant App

activate Vista
Vista -> VistaTutorial: Usuario presiona el botón "Volver al menú"
activate VistaTutorial
VistaTutorial -> App: Cambia a la escena del menú
activate App
App -> App: Cargar FXML del menú
App -> VistaMenu: Inicia Vista del menú
activate VistaMenu
deactivate App
deactivate VistaMenu
deactivate VistaTutorial
deactivate Vista

@enduml